apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - image: ubuntu-sleeper
      name: ubuntu-sleeper
      command: ["sleep2.0"] #to overwrite the entrypoint of dockerfile
      args: ["10"] #pass args to CMD, or overwrite defauld CMD arguement of dockerfile
