apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["shuf -1 0-100 -n 1 >> /opt/number.out;"]
      volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes: # path inside the host (node)
  - name: data-volume
    hostPath:
      path: /data
      type: Directory
    # for a persistent volume condifuration
    # name: mypd
    # persistentVolumeClaim:
    #   claimName: myclaim