apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath: #not to be used in prod env
    path: /tmp/data
  # or replace hostPath with supported solutions
  # awsElastickBlockStore:
  #   volumeID: <volume-id>
  #   fsType: ext4

