apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim2
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # to attach a storageClass definition
  # storageClassName: google-storage 
