apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  #how many times to run completelly
  #if one fails there will be another job initialized
  completions: 3
  #how many jobs run in parallel
  parallelism: 3
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never 

